### ISSUE TITLE
Rwt_nav move_base/goal

### ISSUE THREAD

**Issue by YXGuan** [tork-a/visualization_rwt#118]
Does anyone know how to launch the amcl node and move_base node?.

I would really appreciate your help : )
![Screenshot from 2022-02-19 20-08-24](https://user-images.githubusercontent.com/55643200/154827613-b17f9699-f286-455d-8130-3bc5a5ef91e5.png)

**Comment by k-okada** [comment]
rwt_nav` is designed independent from specific robot, so you need to start amcl/move_base node by your robot's specific launch file.

**Comment by YXGuan** [comment]
Thanks for your reply. 

I was running turtle bot simulation on top of rwt_nav.
https://github.com/ROBOTIS-GIT/turtlebot3/tree/master/turtlebot3_navigation/launch

I can see position(pose) status update but the robot does not move when I set goal from the browser. Is this because there are two /move_base/goal running at the same time?



Here's a list of commands that I run:
- roslaunch rwt_nav rwt_nav.launch 
- roslaunch turtlebot3_gazebo turtlebot3_world.launch  
- roslaunch turtlebot3_navigation turtlebot3_navigation.launch (which includes RVIZ)
- rosrun rwt_nav robot_pose_publisher

**Comment by k-okada** [comment]
@YXGuan Sorry, we need https://github.com/tork-a/visualization_rwt/pull/119/files to navigate through the web gui.

**Comment by YXGuan** [comment]
That solves the issue. Thank you so much professor!
