### ISSUE TITLE
[Noetic] Package rwt_app_chooser fails to build on all platforms

### ISSUE THREAD

**Issue by sloretz** [tork-a/visualization_rwt#129]
Hello @k-okada,

It looks like the package `rwt_app_chooser` is not building on any platform on the ROS Noetic buildfarm.

• [Ubuntu Focal amd64](https://build.ros.org/view/Nbin_uF64/job/Nbin_uF64__rwt_app_chooser__ubuntu_focal_amd64__binary/)
• [Ubuntu Focal armhf](https://build.ros.org/job/Nbin_ufv8_uFv8__rwt_app_chooser__ubuntu_focal_arm64__binary/)
• [Ubuntu Focal armv8](https://build.ros.org/job/Nbin_ufhf_uFhf__rwt_app_chooser__ubuntu_focal_armhf__binary/)

I am removing the release of this package and the dependant package visualization_rwt from Noetic so the buildfarm doesn't keep trying to build it. Please make another release with `bloom-release` once the build failure is fixed.

**Comment by k-okada** [comment]
@sloretz https://github.com/tork-a/visualization_rwt/pull/130/files fixes the problem and I'll release newer version once @sktometometo fixed the https://github.com/tork-a/visualization_rwt/pull/117

**Comment by k-okada** [comment]
@sloretz released new version at  https://github.com/k-okada/rosdistro/pull/new/bloom-visualization_rwt-2

**Comment by k-okada** [comment]
It seems working now

https://build.ros.org/job/Nsrc_uF__visualization_rwt__ubuntu_focal__source/
