### ISSUE TITLE
Catkinize and release visualization_rwt?

### ISSUE THREAD

**Issue by 130s** [tork-a/visualization_rwt#20]
Depending on the answer in https://github.com/tork-a/rwt_ros/issues/4. 

I'm happy to do the work if the answer is yes.

**Comment by garaemon** [comment]
@furushchev working on this issue

**Comment by 130s** [comment]
Same comment from me [there](https://github.com/tork-a/rwt_ros/issues/4#issuecomment-41493170) might apply here too.

**Comment by 130s** [comment]
@furushchev Is this work still in progress?

**Comment by furushchev** [comment]
I think it's good to close this issue.

**Comment by 130s** [comment]
Addressed in https://github.com/tork-a/visualization_rwt/pull/32
