### ISSUE TITLE
rwt_voice_message

### ISSUE THREAD

**Issue by furushchev** [tork-a/visualization_rwt#21]
HTML5のSpeechRecognition APIというSpeech-To-Textを使って音声を文字情報に変換し、ROS Messageとして送るwebアプリを作成しました。
こちらにマージさせていただけると便利だと思います。
(visualizationなのかと言われると疑問ですが）

HTML5として規約はありますが、現在対応しているのはChrome(PC, Android)とOperaNextのみのようです。
またこのアプリが利用しているrosbridge_webserverに、日本語・キリル文字を含む非ASCII文字を送れないというバグがあることがわかっています。
groovy, hydroでは既に修正したプルリクエストが承認されましたが、aptで入るものに適用されたのかはまだ確認していません。

**Comment by 130s** [comment]
@furushchev ありがとうございます．コードを見たいのですが pull request を開けてもらえますか？

visualization のネーミングは，そうですねえ，多分盲点だったんじゃないでしょうか．考えても良いのかも．

**Comment by furushchev** [comment]
pull reqesutを開けるというのは、こちらのrepositoryにpull requestを送るということでしょうか？

**Comment by 130s** [comment]
はい，御願いします．
