### ISSUE TITLE
invalid dependency

### ISSUE THREAD

**Issue by dirk-thomas** [tork-a/visualization_rwt#52]
https://github.com/tork-a/visualization_rwt/blob/1c4aec0e50f6b14137b3cb0f5f244c45d9f69fda/rwt_image_view/package.xml#L18 is not a valid rosdep key. Please either add it to the rosdep database or remove the source entry of the repository from the rosdistro distribution file since the devel job can never succeed.

**Comment by 130s** [comment]
Thanks for pointing this out. rwt\* repositories should've not been meant to be built on ROS farm (as of now at least). With https://github.com/ros/rosdistro/issues/7257, this should be fixed from next devel job.
