### ISSUE TITLE
Indigo compatibility?

### ISSUE THREAD

**Issue by mdrx-io** [tork-a/visualization_rwt#54]
Are there plans to upgrade this package to work with Indigo?

**Comment by 130s** [comment]
Can't think of any reason why packages here don't work with ROS Indigo. Are you getting specific problems?

**Comment by mdrx-io** [comment]
Sorry, the name of the default branch being hydro-devel through me off. No problems once I compiled it myself.

**Comment by 130s** [comment]
Oh, kay. I can't remember either why we had to create distro-specific branches back then. Maybe we can go agnostic.
